on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: ğŸ‘·â€â™€ï¸ Builds successfully
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@HEAD
        with:
          working-directory: frontend
      - run: npm run build
        working-directory: frontend

  unit-tests:
    runs-on: ubuntu-latest
    name: ğŸš§ Unit tests pass
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@HEAD
        with:
          working-directory: frontend
      - run: npm run test
        working-directory: frontend