on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: ğŸ‘·â€â™€ï¸ Builds successfully
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install
      - run: yarn build:app

  unit-tests:
    runs-on: ubuntu-latest
    name: ğŸš§ Unit tests pass
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install
      - run: yarn test:app