on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: ğŸ‘·â€â™€ï¸ Builds successfully
    steps:
      - uses: actions/checkout@v2
      - uses: sergioramos/yarn-actions/install@v6
        with:
          version: true
      - run: yarn build:app

  unit-tests:
    runs-on: ubuntu-latest
    name: ğŸš§ Unit tests pass
    steps:
      - uses: actions/checkout@v2
      - uses: sergioramos/yarn-actions/install@v6
        with:
            version: true
      - run: yarn test:app