on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: ğŸ‘·â€â™€ï¸ Builds successfully
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1.6.0
      - run: npm run build

  unit-tests:
    runs-on: ubuntu-latest
    name: ğŸš§ Unit tests pass
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1.6.0
      - run: npm run test